name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          
      - name: installing angular
        run : npm i @angular/cli

      - name: create dist folder
        run: ng build --prod --base-href "https://ganapathirao.github.io/sabka-bazaar/"
        
      - name: deploying
        run: ngh --dir dist/sabka-bazaar
        
